---
- hosts: dev

  vars:
    server_name: ohmydev.tk
    gitlab_server_name: git.ohmydev.tk
    gitlab_email_from: git@ohmydev.tk
    gitlab_path: /home/git/gitlab
    mysql_root_password: root
    swap_size: 512k

  roles:
    - init
    - swap
    - postfix
    - git
    - nginx
    - php
    - composer
    - mysql
    - zsh
    - ruby
    - gitlab
