- name: create file
  shell: >
    creates=/swapfile
    dd if=/dev/zero of=/swapfile bs=1024 count=512k
    mkswap /swapfile
    swapon /swapfile

- name: autorun
  mount: name=swap src=/swapfile fstype=swap state=present
