- name: install package
  apt: pkg=git state=latest

- name: create user
  user: name={{git_user}} createhome=yes

- name: setup username
  command: git config --global user.name "{{git_user}}"

- name: setup email
  command: git config --global user.email "{{git_user}}@{{server_name}}"

- name: setup authorized_keys
  authorized_key: user=git key="{{item}}"
  with_file:
    - ../../../public_keys/intellectsoft
    - ../../../public_keys/winhome
