- name: update apt repo
  apt: upgrade=yes update_cache=yes cache_valid_time=3600

- name: install packages
  apt: pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - curl
    - htop
    - tcpdump
    - mc
    - wget
    - vim